# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For the this part of the assignment you will need to submit the implementation for an agent which can solve sudoku puzzles – this notebook:
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

I suggest you implement *constraint satisfaction* as it is described in the unit material. You can use the code you have previously been given as a guide. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%).

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (report), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [1]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [2]:
def sudoku_solver(sudoku):
    """
    Solves a Sudoku puzzle and returns its unique solution.

    Input
        sudoku : 9x9 numpy array
            Empty cells are designated by 0.

    Output
        9x9 numpy array of integers
            It contains the solution, if there is one. If there is no solution, all array entries should be -1.
    """
    solved_sudoku = None  # Will hold the final solved sudoku board.
    # build exact cover model 
    model = ExactCoverModel(sudoku)
    
   # check for conflict in the initial given values 
    if not model.solution_labels and np.any(sudoku != 0):
        # if there are given numbers but no valid initial assignments, the puzzle is unsolvable.
        solved_sudoku = -np.ones((9, 9), dtype=int)
    else:
        # Use Algorithm X (exact cover solver) to solve the sudoku.
        solver = ExactCoverSolver(model)
        solution_model = solver.search()
        
        if solution_model is None:
            # if no solution is found, mark as unsolvable.
            solved_sudoku = -np.ones((9, 9), dtype=int)
        else:
           # construct the solved sudoku grid
            solved_sudoku = np.zeros((9, 9), dtype=int)
            for row, col, digit in solution_model.solution_labels:
                solved_sudoku[row, col] = digit

    return solved_sudoku


class ExactCoverSolver:
    """
    Uses recursive backtracking (Algorithm X) to search for a complete solution
    within an ExactCoverModel.
    """
    def __init__(self, model: 'ExactCoverModel'):
        self.model = model

    def search(self):
        # If all constraints are satisfied, the sudoku is solved.
        if self.model.constraints_satisfied():
            return self.model

        # heuristic: select the constraint (column) with the fewest available candidates.
        candidates = self.model.MRV_select_candidate_rows()
        if not candidates:
            return None

        # try each candidate recursively.
        for cand in candidates:
            self.model.choose_candidate(cand)
            result = self.search()
            if result:
                return result
            # backtrack if the candidate did not lead to a solution.
            self.model.revert_last_choice()
        return None


class ExactCoverModel:
    """
    Constructs the exact cover model for the sudoku
    
    Each candidate (columns 0 to 728) represents placing a digit in a cell and satisfies:
      1. Cell constraint (cell must be filled)
      2. Row constraint (digit appears once in the row)
      3. Column constraint (digit appears once in the column)
      4. Box constraint (digit appears once in the 3x3 block)
    
    Data Structures:
      - constraint_map: Maps each constraint index (0 to 323) to a list of candidate IDs.
      - assignment_matrix: A 729x4 array where each row lists the four constraints
                           a candidate satisfies
      - solution_labels: List of (row, col, digit) tuples for chosen candidates
      - removed_candidates: Stack that keeps track of modifications for backtracking
    """
    def __init__(self, sudoku):
        # initialize constraint_map for 324 constraints (0 to 323)
        self.constraint_map = {i: [] for i in range(324)}
        # allocate assignment_matrix for all 729 candidates
        self.assignment_matrix = np.empty((729, 4), dtype=int)
        # list of chosen candidates as (row, col, digit) tuples
        self.solution_labels = []
        # stack to save modifications for backtracking
        self.removed_candidates = []
        # populate the model and then process the initial givens
        self._populate_model_and_rows()
        self._process_initial_givens(sudoku)

    def label_from_candidate(self, candidate):
        """
        Converts a candidate ID (0-728) into a (row, col, digit) tuple
        """
        row = candidate // 81
        col = (candidate % 81) // 9
        digit = (candidate % 9) + 1
        return (row, col, digit)

    def constraints_satisfied(self):
        """
        Returns True if all constraints are satisfied (constraint_map is empty)
        """
        return not self.constraint_map

    def MRV_select_candidate_rows(self):
        """
        Selects and returns candidate rows from the constraint with the fewest candidates (MRV heuristic)
        This heuristic speeds up the recursive search
        """
        if not self.constraint_map:
            return []
        min_key = min(self.constraint_map, key=lambda k: len(self.constraint_map[k]))
        return self.constraint_map[min_key]

    def choose_candidate(self, candidate):
        """
        Chooses a candidate (a digit assignment) and updates the model. The modifications are done in place and a backup is stored for later reversion
        """
        # get the constraints that the candidate satisfies
        constraints = self.assignment_matrix[candidate]
        
        # compute all candidates that conflict with this candidate
        conflicting = set()
        for con in constraints:
            conflicting.update(self.constraint_map.get(con, []))
        
        # add the chosen candidate to solution_labels
        self.solution_labels.append(self.label_from_candidate(candidate))
        
        # backup list to store modifications.
        # each backup entry is a tuple: (constraint, was_deleted, original_list)
        backup = []
        
        # first remove constraints satisfied by this candidate.
        for con in constraints:
            if con in self.constraint_map:
                backup.append((con, True, self.constraint_map[con][:]))
                del self.constraint_map[con]
                
        # second for the remaining constraints, remove candidates that conflict.
        for con in list(self.constraint_map.keys()):
            old_list = self.constraint_map[con][:]
            new_list = [cand for cand in old_list if cand not in conflicting]
            if len(new_list) != len(old_list):
                backup.append((con, False, old_list))
                self.constraint_map[con] = new_list
        
        # save the backup so that these changes can be reverted later.
        self.removed_candidates.append(backup)

    def revert_last_choice(self):
        """
        Reverts the most recent candidate selection (backtracking) by:
          - Removing the candidate's label from solution_labels
          - Restoring the previous state of constraint_map using the stored backup
        """
        if self.solution_labels:
            self.solution_labels.pop()
        if self.removed_candidates:
            backup = self.removed_candidates.pop()
            for con, was_deleted, original_list in backup:
                self.constraint_map[con] = original_list

    # helper methods: 
    def _populate_model_and_rows(self):
        """
        For each candidate (0-728), compute its four constraint indices:
        
        Updates:
          - assignment_matrix with the computed constraints.
          - constraint_map by appending candidate IDs to each corresponding constraint.
        """
        for candidate in range(729):
            row = candidate // 81
            col = (candidate % 81) // 9
            digit = candidate % 9  # 0-based - label_from_candidate adds 1
            
            cell_index = row * 9 + col
            row_constraint = 81 + row * 9 + digit
            col_constraint = 162 + col * 9 + digit
            box_constraint = 243 + (row // 3) * 27 + (col // 3) * 9 + digit

            # add candidate to each corresponding constraint list
            self.constraint_map[cell_index].append(candidate)
            self.constraint_map[row_constraint].append(candidate)
            self.constraint_map[col_constraint].append(candidate)
            self.constraint_map[box_constraint].append(candidate)
            
            # store the candidate's constraints
            self.assignment_matrix[candidate] = [cell_index, row_constraint, col_constraint, box_constraint]

    def _detect_conflicts(self, candidates):
        """
        Given a list of candidate rows (from the initial givens), check if any constraint 
        is satisfied more than once.
        
        Returns:
          - A set of constraints covered by the candidates.
          - A boolean indicating whether a conflict was detected.
        """
        constraints = [con for cand in candidates for con in self.assignment_matrix[cand]]
        return set(constraints), (len(constraints) != len(set(constraints)))

    def _process_initial_givens(self, sudoku):
        """
        Processes the initial givens (nonzero cells) in the sudoku puzzle
        """
        # determine candidate rows corresponding to each nonzero cell
        initial = [
            i * 81 + j * 9 + (val - 1)
            for i, row in enumerate(sudoku)
            for j, val in enumerate(row) if val
        ]
        
        # check for any conflicts among the initial candidates
        remove_cons, conflict = self._detect_conflicts(initial)
        if conflict:
            # if a conflict exists, mark the puzzle as unsolvable
            self.solution_labels = []
            return
        
        # record each given's candidate assignment
        for cand in initial:
            self.solution_labels.append(self.label_from_candidate(cand))
        
        # identify all candidates that conflict with the given assignments
        conflict_cands = {cand for con in remove_cons for cand in self.constraint_map.get(con, [])}
        
        # remove the conflicting candidates and satisfied constraints
        self.constraint_map = {
            con: [cand for cand in cands if cand not in conflict_cands]
            for con, cands in self.constraint_map.items() if con not in remove_cons
        }




All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 30 seconds each on the test machine to count as successful, but you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [3]:
SKIP_TESTS = True

if not SKIP_TESTS:
    import time
    import numpy as np
    __SCORES = {}
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            if not isinstance(your_solution, np.ndarray):
                print("\033[91m[ERROR] Your sudoku_solver function returned a variable that has the incorrect type. If you submit this it will likely fail the auto-marking procedure result in a mark of 0 as it is expecting the function to return a numpy array with a shape (9,9).\n\t\033[94mYour function returns a {} object when {} was expected.\n\x1b[m".format(type(your_solution), np.ndarray))
            elif not np.all(your_solution.shape == (9, 9)):
                print("\033[91m[ERROR] Your sudoku_solver function returned an array that has the incorrect shape.  If you submit this it will likely fail the auto-marking procedure result in a mark of 0 as it is expecting the function to return a numpy array with a shape (9,9).\n\t\033[94mYour function returns an array with shape {} when {} was expected.\n\x1b[m".format(your_solution.shape, (9, 9)))
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took {} seconds to solve.\n".format(end_time-start_time))

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        __SCORES[difficulty] = {
            'correct': count,
            'total': len(sudokus)
        }

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [4]:
import sys
import pathlib

fail = False;

success = '\033[1;32m[✓]\033[0m'
issue = '\033[1;33m[!]'
error = '\033[1;31m\t✗'
indent_success = '\033[1;32m\t✓'

#######
##
## Skip Tests check.
##
## Test to ensure the SKIP_TESTS variable is set to True to prevent it slowing down the automarker.
##
#######

if not SKIP_TESTS:
    fail = True;
    print("{} \'SKIP_TESTS\' is incorrectly set to False.\033[0m".format(issue))
    print("{} You must set the SKIP_TESTS constant to True in the cell above.\033[0m".format(error))
else:
    print('{} \'SKIP_TESTS\' is set to true.\033[0m'.format(success))

#######
##
## Report File Check.
##
## Test that checks there is a report pdf file found in the same folder as the notebook. This is required by the coursework specification.
##
#######

p1 = pathlib.Path('./report.pdf')
p2 = pathlib.Path('./Report.pdf')
if not (p1.is_file() or p2.is_file()):
    fail = True;
    print("{} Report PDF not found.\033[0m".format(issue))
    print("{} You must include a separate file called report.pdf in your submission.\033[0m".format(error))
else:
    print('{} Report PDF found.\033[0m'.format(success))

#######
##
## File Name check.
##
## Test to ensure file has the correct name. This is important for the marking system to correctly process the submission.
##
#######
    
p3 = pathlib.Path('./sudoku.ipynb')
if not p3.is_file():
    fail = True
    print("{} The notebook name is incorrect.\033[0m".format(issue))
    print("{} This notebook file must be named sudoku.ipynb\033[0m".format(error))
else:
    print('{} The notebook name is correct.\033[0m'.format(success))

#######
##
## Create classifier function check.
##
## Test that checks the create_classifier function exists. The function should train the classifier and return it so that it can be evaluated by the marking system.
##
#######

if "sudoku_solver" not in dir():
    fail = True;
    print("{} The sudoku_solver function has not been defined.\033[0m".format(issue))
    print("{} Your code must include a sudoku_solver function as described in the coursework specification.\033[0m".format(error))
    print("{} If you believe you have, \'restart & run-all\' to clear this error.\033[0m".format(error))
else:
    print('{} The sudoku_solver function has been defined.\033[0m'.format(success))



try:
    _sudoku = np.load("data/very_easy_puzzle.npy")[0]
    _solution = np.load("data/very_easy_solution.npy")[0]

    if not np.array_equal(sudoku_solver(_sudoku), _solution):
        print("{} Your sudoku_solver function does not correctly solve the first sudoku.\033[0m".format(issue))
        print()
        print("{} Your assignment is unlikely to get any marks from the autograder. While we will\033[0m".format(error))
        print("{} try to check it manually to assign some partial credit, we encourage you to ask\033[0m".format(error))
        print("{} for help on the forum or directly to a tutor.\033[0m".format(error))
        print()
        print("{} Please use the report file to explain your code anyway.\033[0m".format(error))
    else:
        print("{} Your sudoku_solver function correctly solves the first sudoku.\033[0m".format(success))
        if "__SCORES" in dir():
#             print("{} Test set summary - Not Found.\033[0m".format(issue))
#             print("{} Test set summary could not be found. This is automatically generated when the \033[0m".format(error))
#             print("{} above test cell is run. If you would like to see the summary please run the above cell.\033[0m".format(error))
#             print("{} You do not need this for submission, it is only for your convenience.\033[0m".format(error))
#         else:
            correct = 0
            total = 0
            for key, value in __SCORES.items():
                correct += value['correct']
                total += value['total']
                
            print("{} Test set summary - {}/{} Correct.\033[0m".format(issue, correct, total))
            if total != correct:
                
                for key, value in __SCORES.items():
                    if value['correct'] == value['total']:
                        print("{} {}/{} of {} sudokus correct.\033[0m".format(indent_success, value['correct'], value['total'], key))
                    else:
                        print("{} {}/{} of {} sudokus correct.\033[0m".format(error, value['correct'], value['total'], key))
            
except Exception as e:
    fail = True
    print("{} Error running test set.\033[0m".format(issue))
    print("{} Your code produced the following error. This error will result in a zero from the automarker, please fix.\033[0m".format(error))
    print(e)

    

#######
##
## Final Summary
##
## Prints the final results of the submission tests.
##
#######

if fail:
    sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
else:
    print("\033[1m\n\n")
    print("╔═══════════════════════════════════════════════════════════════╗")
    print("║                        Congratulations!                       ║")
    print("║                                                               ║")
    print("║            Your work meets all the required criteria          ║")
    print("║                   and is ready for submission.                ║")
    print("╚═══════════════════════════════════════════════════════════════╝")
    print("\033[0m")
    

[✓] 'SKIP_TESTS' is set to true.
[✓] Report PDF found.
[✓] The notebook name is correct.
[✓] The sudoku_solver function has been defined.
[✓] Your sudoku_solver function correctly solves the first sudoku.



╔═══════════════════════════════════════════════════════════════╗
║                        Congratulations!                       ║
║                                                               ║
║            Your work meets all the required criteria          ║
║                   and is ready for submission.                ║
╚═══════════════════════════════════════════════════════════════╝



In [5]:
# This is a TEST CELL. Do not delete or change.